### ISSUE TITLE
Update README.md for Project Enhancement

### ISSUE THREAD

**Issue by Uzzal-Bhowmik** [Uzzal-Bhowmik/space-quora-react#1]
We need to enhance the README.md file for our project to provide better documentation and make it more user-friendly. The current README lacks important information and structure, and it's essential to improve it to help our users and contributors understand and use our project effectively.

## Proposed Changes:
- Provide relevant pictures or screenshots of the tools.
- Provide a clear project overview and working procedure.
- Explain how to use the project.
- Add code examples or usage scenarios (if needed).
- Document any prerequisites or dependencies.
- Include licensing information.
- Mention how to contribute to the project as well.

Additional Context:
Add any relevant information or context about the project, such as links (related to API), or related issues.

**Comment by sakhwt** [comment]
I'm excited to contribute to the README and help make the project even better. I have experience writing documentation and I'm familiar with the project. Thanks. 😍

**Comment by Uzzal-Bhowmik** [comment]
readme file has been updated
